#!/bin/bash

# script to make flatpak-node-generator work

set -euo pipefail

MY_DIR="$(dirname "$0")"
MANIFEST_ROOT="$(realpath "$MY_DIR/..")"

if [[ ! -f "package-lock.json" || ! -f "package.json" || $(jq -r '.name' < package.json) != insomnia ]]; then
    echo 'This script must be run in the root directory of https://github.com/Kong/insomnia.git.'
    exit 1
fi

if [[ ! -d '../grpc-reflection-js' || $(jq -r '.name' < ../grpc-reflection-js/package.json) != grpc-reflection-js ]]; then
    echo 'Please make sure a checkout of https://github.com/jackkav/grpc-reflection-js is available at ../grpc-reflection-js.'
    exit 1
fi

# retrieve the commit hash
p0_resolved="$(jq -r '.packages.["node_modules/grpc-reflection-js"].resolved' < package-lock.json)"
if [[ $p0_resolved != "git+ssh://git@github.com/jackkav/grpc-reflection-js.git#"* ]]; then
    echo 'Unexpected resolved URL, please inspect'
    exit 1
fi
p0_git_hash="${p0_resolved##*#}"

# generate flatpak sources for grpc-reflection-js
pushd '../grpc-reflection-js' >/dev/null
git checkout -q "$p0_git_hash"
flatpak-node-generator yarn yarn.lock
mv generated-sources.json "$MANIFEST_ROOT/grpc-reflection-js-generated-sources.json"
popd >/dev/null

# update package.json
jq '.dependencies["grpc-reflection-js"] |= "file:../../../grpc-reflection-js"' <<<"$(<packages/insomnia/package.json)" > packages/insomnia/package.json

# refresh package-lock.json
npm install --package-lock-only --no-audit --no-fund

# generate flatpak sources for insomnia
flatpak-node-generator --electron-node-headers -r npm package-lock.json
mv generated-sources.json "$MANIFEST_ROOT/insomnia-generated-sources.json"

# generate patch
mkdir -p "$MANIFEST_ROOT/patches"
git diff > "$MANIFEST_ROOT/patches/sources.patch"
